name: 'Security Update Checker for PHP and Drupal packages'
description: 'Checks composer.json for known available security updates in your package dependencies'
branding:
  icon: 'bell'
  color: 'red'
inputs:
  lock:
    description: 'The path to composer.lock is stored (root directory by default)'
    required: false
    default: './composer.lock'
  format:
    description: 'The output format (json by default, supported: markdown, json, print_r, or yaml)'
    required: false
    default: json
outputs:
  updates:
    description: 'The detected security updates as JSON'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "/checker"
    - "--format"
    - ${{ inputs.format }}
    - "--lock"
    - ${{ inputs.lock }}
