name: 'The PHP Security Checker'
description: 'Checks composer.json for known vulnerabilities in your package dependencies'
branding:
  icon: 'bell'
  color: 'red'
inputs:
  lock:
    description: 'The path to composer.lock is stored (root directory by default)'
    required: false
    default: './composer.lock'
  format:
    description: 'The output format (json by default, supported: markdown, json, or yaml)'
    required: false
    default: json
  disable-exit-code:
    description: 'Whether to continue when issues are detected (false by default)'
    required: false
    default: 0
outputs:
  vulns:
    description: 'The detected vulnerabilities as JSON'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "check"
    - "--format"
    - ${{ inputs.format }}
    - "--path"
    - ${{ inputs.lock }}
    - "--disable-exit-code=${{ inputs.disable-exit-code }}"
