#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use App\Command\CheckerCommand;
use App\Command\DrupalDataCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new CheckerCommand());
$application->add(new DrupalDataCommand());
$application->run();
