#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use App\Command\CheckCommand;
use App\Command\DrupalDataCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new CheckCommand());
$application->run();
