#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use App\Command\CheckCommand;
use Symfony\Component\Console\Application;

$app = new Application();
$check = new CheckCommand();
$app->add($check);
$app->setDefaultCommand($check->getName(), true);
$app->run();
