on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-action.yml'
      - '.github/ISSUE_TEMPLATE_SEC.md'
      - 'tests/**'
  schedule:
    - cron:  '0 0 * * *' # UTC == 2 AM EET

name: Test Action

jobs:

  test-action:

    env:
      EXPECTED_DRUPAL_UPDATE: 9.2.18

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: druidfi/security-checker-action@main
        name: Test main branch
        with:
          lock: tests/repo/composer.lock
          format: markdown
        id: security-updates

      - uses: dblock/create-a-github-issue@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BODY: "${{ steps.security-updates.outputs.updates }}"
        with:
          update_existing: true
          filename: .github/ISSUE_TEMPLATE_SEC.md

      - uses: druidfi/security-checker-action@v1
        name: Test v1 tag
        with:
          lock: tests/repo/composer.lock
          format: json
        id: security-updates-v1

      - name: Extract a value from JSON
        run: |
          version=$( echo '${{ steps.security-updates-v1.outputs.updates }}' | jq -r '.["drupal/core"].update_to' )
          echo "::set-output name=test::$version"
        id: value-from-json

      - name: Fail if JSON has incorrect data
        if: steps.value-from-json.outputs.test != ${{ env.EXPECTED_DRUPAL_UPDATE }}
        run: |
          echo "::error::JSON does not have correct value: ${{ steps.value-from-json.outputs.test }} instead of ${{ env.EXPECTED_DRUPAL_UPDATE }}."
          exit 1
