on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-action.yml'
      - '.github/ISSUE_TEMPLATE_SEC.md'
      - 'tests/**'

name: Test Action

jobs:

  test-action:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: druidfi/security-checker-action@main
        name: Test main branch
        with:
          lock: tests/repo/composer.lock
          format: markdown
        id: security-updates

      - uses: dblock/create-a-github-issue@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BODY: "${{ steps.security-updates.outputs.updates }}"
        with:
          update_existing: true
          filename: .github/ISSUE_TEMPLATE_SEC.md

      - uses: druidfi/security-checker-action@v1
        name: Test v1 tag
        with:
          lock: tests/repo/composer.lock
          format: json
        id: security-updates-v1

      - name: Extract a value from JSON
        run: echo "::set-output name=test::${{ steps.security-updates-v1.outputs.updates }} | jq '.["drupal/core"].update_to'"
        id: value-from-json

      - name: Check if JSON has correct data
        if: steps.value-from-json.outputs.test != '9.3.12'
        run: exit 1
