on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-action.yaml'
      - 'src/**'
      - 'tests/**'

name: Test Action

jobs:

  test-action:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: druidfi/security-checker-action@main
        with:
          lock: tests/repo/composer.lock
        id: updates

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTENT: ${{ steps.updates.outputs.updates }}
        with:
          update_existing: true
          filename: .github/ISSUE_TEMPLATE_SEC.md
