on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-action.yml'
      - '.github/ISSUE_TEMPLATE_SEC.md'
      - 'tests/**'

name: Test Action

jobs:

  test-action:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ v1, main ]

    steps:

      - uses: actions/checkout@v3

      - uses: "druidfi/security-checker-action@${{ matrix.version }}"
        with:
          lock: tests/repo/composer.lock
          format: markdown
        id: security-updates

      - uses: dblock/create-a-github-issue@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BODY: "${{ steps.security-updates.outputs.updates }}"
        with:
          update_existing: true
          filename: .github/ISSUE_TEMPLATE_SEC.md
        if: version == 'main'
